CREATE DATABASE IF NOT EXISTS db_buku;
USE db_buku;
CREATE TABLE IF NOT EXISTS buku (
  id INT AUTO_INCREMENT PRIMARY KEY,
  judul VARCHAR(200) NOT NULL,
  pengarang VARCHAR(100) NOT NULL,
  tahun INT NOT NULL,
  foto VARCHAR(255) NOT NULL
);
